apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: windocks-dotnetapi
spec:
  replicas: 1  
  template:
    metadata:
      labels:
        app: dotnetapi
    spec:
      containers:
        - image: "windocks/windocks-redis-demo-dotnetapi:1.0.2"
          imagePullPolicy: Always
          name: dotnetapi
          ports:
            - containerPort: 5003